#!  /bin/bash

# Disable tea-break notifications by removing the file that signals that
# the alarm is enabled.
#
# Author: Matthew Signorini <matthew.signorini@gmail.com>


export ENABLED_FILE=/tmp/tea-break/alarm-enabled

if [ -e ${ENABLED_FILE} ]
then
    rm -f ${ENABLED_FILE}

    if [ -e /tmp/tea-break/crontab.old ]
    then
        cat /tmp/tea-break/crontab.old | crontab -
    else
        echo "" | crontab -
    fi
fi

# vim: ft=sh ts=4 sw=4 et
