#!  /bin/bash

# Disable tea-break notifications by removing the file that signals that
# the alarm is enabled.
#
# Author: Matthew Signorini <matthew.signorini@gmail.com>


export ENABLED_FILE=/var/run/tea-break/alarm-enabled

if [ -e ${ENABLED_FILE} ]
then
    rm -f ${ENABLED_FILE}
    chmod 600 ~/.Xauthority
fi

# vim: ft=sh ts=4 sw=4 et
