#!  /bin/bash

# Enable notifications from tea-break, a system to generate periodic
# notifications to take a break from one's screen time.
#
# Author: Matthew Signorini <matthew.signorini@gmail.com>


PREFIX=/usr/local

ENABLED_FILE=/tmp/tea-break/alarm-enabled
ALERT_SCRIPT=${PREFIX}/share/tea-break/tea-break.sh
CRON_SCRIPT="0 * * * * env DISPLAY=${DISPLAY} XAUTHORITY=${XAUTHORITY} ${ALERT_SCRIPT}\n"

if [ ! -d /tmp/tea-break ]
then
    mkdir /tmp/tea-break
fi

if [ ! -e ${ENABLED_FILE} ]
then
    touch ${ENABLED_FILE}
    OLD_CRONTAB=`crontab -l`

    if [ $? = 0 ]
    then
        echo -e "${OLD_CRONTAB}" > /tmp/tea-break/crontab.old
    fi

    echo -e "${CRON_SCRIPT}" | crontab
fi

# vim: ft=sh ts=4 sw=4 et
