#!  /bin/bash

# Enable notifications from tea-break, a system to generate periodic
# notifications to take a break from one's screen time.
#
# Author: Matthew Signorini <matthew.signorini@gmail.com>


PREFIX=/usr/local

ENABLED_FILE=/tmp/tea-break/alarm-enabled
ALERT_SCRIPT=${PREFIX}/lib/tea-break/tea-break.sh
CRON_SCRIPT="0 * * * * env DISPLAY=${DISPLAY} XAUTHORITY=${XAUTHORITY} ${ALERT_SCRIPT}\n"

if [ ! -d /tmp/tea-break ]
then
    mkdir /tmp/tea-break
fi

# the program that generates a notification pop up window is run every
# hour via a script in /etc/cron.hourly. That script will check the
# existence of a file to determine whether notifications are enabled.
if [ ! -e ${ENABLED_FILE} ]
then
    touch ${ENABLED_FILE}
    echo -e "Installing cron script:\n${CRON_SCRIPT}"
    echo -e "${CRON_SCRIPT}" | crontab
fi

# vim: ft=sh ts=4 sw=4 et
